---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "gateway-api"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "gateway-api"
  source:
    repoURL: "https://github.com/kubernetes-sigs/gateway-api"
    path: "config/crd"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "gateway-api"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
...
