---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "httpbin"
  namespace: "argocd"
spec:
  source:
    repoURL: "git@github.com:itc64-dev/test-gitops.git"
    targetRevision: "feature/update"
    path: "etc/dev/applications/httpbin/kustomize/nodeport"
...
