---
apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "ca-selfsigned"
  namespace: "cert-manager"
spec:
  isCA: true
  commonName: "ca-selfsigned"
  secretName: "ca-selfsigned"
  privateKey:
    algorithm: "ECDSA"
    size: 256
  issuerRef:
    name: "selfsigned"
    kind: "ClusterIssuer"
    group: "cert-manager.io"
...
