---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../../../etc/dev/metrics-server/argocd"
  - "../../../../etc/dev/gateway-api/argocd"
  - "../../../../etc/dev/cert-manager/argocd"
...
