---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  #
  # Platform specific
  #
  - "../../../../etc/dev/minikube/argocd"
  #
  # Core modules
  #
  - "../../../../etc/dev/metrics-server/argocd"
  - "../../../../etc/dev/gateway-api/argocd"
  - "../../../../etc/dev/sealed-secrets/argocd"
  - "../../../../etc/dev/cert-manager/argocd"
  #
  # Optional modules
  #
  # disabled # - "../../../../etc/dev/k8s-secrets-store/argocd"
  # disabled # - "../../../../etc/dev/vault/argocd"
  # disabled # - "../../../../etc/dev/opensearch/argocd"
  # disabled # - "../../../../etc/dev/prometheus/argocd-minikube"
  # disabled # - "../../../../etc/dev/fluent-bit/argocd-loki"
  # disabled # - "../../../../etc/dev/loki/argocd-minikube"
  # disabled # - "../../../../etc/dev/grafana/argocd-minikube-loki-prometheus"
...
