---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "cert-manager"
  namespace: "cert-manager"
spec:
  interval: "60m"
  chart:
    spec:
      chart: "cert-manager"
      version: "1.13.*"
      interval: "6h"
...
