---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../src/flagger/kustomize/fluxcd"

patches:
  - path: "namespace.patch.yaml"
  - path: "helm-repository.patch.yaml"
  - path: "helm-release.patch.yaml"
...
