---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "wordpress"
  namespace: "argocd"
spec:
  source:
    targetRevision: "19.0.4"
    helm:
      valuesObject:
        wordpressPassword: "X_PASSWORD_X"
        multisite:
          enable: false
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "300m"
        containerPorts:
          http: 8080
          https: 8443
        service:
          type: ClusterIP
        ingress:
          enabled: false
        persistence:
          enabled: true
          size: 10Gi
        serviceAccount:
          create: true
        metrics:
          enabled: true
        mariadb:
          enabled: true
          architecture: standalone
        memcached:
          enabled: false
        autoscaling:
          enabled: false
...
