---
apiVersion: "argoproj.io/v1alpha1"
kind: "AppProject"
metadata:
  name: "root"
  namespace: "argocd"
spec:
  sourceRepos:
    - '*'
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "*"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
...
