---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "root-kubernetes"
  namespace: "argocd"
spec:
  project: "root"
  source:
    path: "var/dev/argocd/kubernetes"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
...
