---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "app-project.yaml"
  - "application-kubernetes.yaml"
  - "application-infrastructure.yaml"
  - "application-resources.yaml"
  - "application-applications.yaml"
...
