---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "grafana"
  namespace: "argocd"
spec:
  source:
    targetRevision: "7.0.17"
    helm:
      valuesObject:
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 2
          targetCPU: "60"
        persistence:
          type: "pvc"
          enabled: true
        datasources:
          datasources.yaml:
            apiVersion: 1
...
