---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  name: "gateway-api"
  namespace: "flux-system"
spec:
  interval: "1m0s"
  timeout: "5m0s"
  prune: true
  wait: true
  path: "./etc/dev/gateway-api/fluxcd/default"
  dependsOn: []
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
...
