---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "prometheus"
  namespace: "argocd"
spec:
  source:
    targetRevision: "25.8.2"
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        prometheus-node-exporter:
          enabled: true
        server:
          persistentVolume:
            enabled: true
          service:
            enabled: true
            servicePort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1024Mi"
...
