---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "rook-ceph"
  namespace: "rook-ceph"
spec:
  releaseName: "rook-ceph"
  chart:
    spec:
      chart: "rook-ceph"
      sourceRef:
        kind: "HelmRepository"
        name: "rook"
  values: {}
...
