---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "loki"
  namespace: "argocd"
spec:
  source:
    targetRevision: "5.41.2"
    helm:
      valuesObject:
        gateway:
          enabled: true
        singleBinary:
          replicas: 1
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: "filesystem"
          limits_config:
            # Warning: fine-tune values as needed to avoid rate-limit erros
            ingestion_rate_mb: 16
            ingestion_burst_size_mb: 16
          monitoring:
            dashboards:
              enabled: false
...
