---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "namespace-rook-ceph.yaml"
  - "namespace-rook-ceph-cluster.yaml"
  - "helm-repository-rook-ceph.yaml"
  - "helm-repository-rook-ceph-cluster.yaml"
  - "helm-release-rook-ceph.yaml"
  - "helm-release-rook-ceph-cluster.yaml"
...
