---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/infrastructure/istio-system/fluxcd/default"

patches:
  - path: "helm-repository.patch.yaml"
  - path: "helm-release-base.patch.yaml"
  - path: "helm-release-istiod.patch.yaml"
...
