#!/usr/bin/env bash
# Template: 1.1.0
#######################################
# GitHub / Control
#
# Control script for GitHub service
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/gitops64
# Version: 4.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=bin/dev-set
source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }

# shellcheck source=src/infrastructure/gitops64/bl64/shared/setup
source "${DEV_PATH_SRC}/infrastructure/gitops64/bl64/shared/setup" || { echo "Error: unable to load gitops64 bash lib" && exit 1; }

# shellcheck source-path=lib/bl64source
source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-bsh.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-xsv.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64" && exit 1; }

#
# Globals
#

export GITHUB_MAIN_GH_BIN="${GITHUB_MAIN_GH_BIN:-${DEV_LIB_GITHUB_BIN}}"
export GITHUB_MAIN_KEYGEN_BIN="${GITHUB_MAIN_KEYGEN_BIN:-/usr/bin/ssh-keygen}"
export GITHUB_MAIN_BROWSER_BIN="${GITHUB_MAIN_BROWSER_BIN:-NONE}"

#
# Functions
#

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function github_main_key_show() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"
  local repository="${G64_GITHUB_REPOSITORY_OWNER}/${G64_GITHUB_REPOSITORY_NAME}"
  bl64_msg_show_task "show GitHub repository deployment keys (${repository})"
  "$GITHUB_MAIN_GH_BIN" repo deploy-key \
    --repo "$repository" \
    list
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function github_main_key_add() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"
  local repository="${G64_GITHUB_REPOSITORY_OWNER}/${G64_GITHUB_REPOSITORY_NAME}"
  local key_title='GitOps64 Deployment SSH Key'
  local key_private="${DEV_PATH_VAULT}/${environment}/${G64_GITOPS64_KEY_DEPLOYMENT_PRIVATE}"

  bl64_msg_show_task "generate deployment SSH key (${key_private})"
  if [[ -f "$key_private" ]]; then
    bl64_msg_show_warning 'deployment key already created. Reusing existing one.'
  else
    "$GITHUB_MAIN_KEYGEN_BIN" \
      -N '' \
      -t "$G64_GITHUB_API_SSH_TYPE" \
      -C "$key_title" \
      -f "$key_private" ||
      return $?
  fi

  bl64_msg_show_task "add GitHub repository deployment keys (${repository})"
  "$GITHUB_MAIN_GH_BIN" repo deploy-key \
    --repo "$repository" \
    --title "$key_title" \
    add \
    "${key_private}.pub"
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function github_main_key_remove() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"
  local repository="${G64_GITHUB_REPOSITORY_OWNER}/${G64_GITHUB_REPOSITORY_NAME}"
  local key_id="$2"
  bl64_msg_show_task "remove GitHub repository deployment key (${repository}:${key_id})"
  "$GITHUB_MAIN_GH_BIN" repo deploy-key \
    --repo "$repository" \
    delete \
    "$key_id"
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function github_main_login() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'login to GittHub'
  BROWSER="$GITHUB_MAIN_BROWSER_BIN" "$GITHUB_MAIN_GH_BIN" \
    auth login
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function github_main_initialize() {
  bl64_dbg_app_show_function "$@"
  local command="$1"
  local environment="$2"
  local profile="$3"
  local key_id="$4"

  # shellcheck disable=SC2015
  bl64_check_parameter 'command' &&
    bl64_check_parameter 'environment' ||
    { github_main_help && return 1; }

  bl64_check_command "$GITHUB_MAIN_GH_BIN" &&
    bl64_check_command "$GITHUB_MAIN_KEYGEN_BIN" ||
    return $?

  gitops64_initialize "$environment" &&
    gitops64_setup_load "$environment" 'infrastructure/github' "$profile" 'gitops64' &&
    bl64_check_export 'G64_GITHUB_REPOSITORY_NAME' &&
    bl64_check_export 'G64_GITHUB_REPOSITORY_OWNER' &&
    bl64_check_export 'G64_GITOPS64_KEY_DEPLOYMENT_PRIVATE' &&
    bl64_check_export 'G64_GITHUB_API_SSH_TYPE' ||
    return $?

  if [[ "$command" == 'key_remove' ]]; then
    bl64_check_parameter 'key_id' 'please specify the key-id to remove (-i)'
  fi
}

#######################################
# Show script usage description
#
# Arguments:
#   None
# Outputs:
#   Command line format and description
# Returns:
#   0
#######################################
function github_main_help() {
  bl64_msg_show_usage \
    '<-l|-s|-a|-r> -e Environment -p Profile [-i KeyID] [-V Verbose] [-D Debug] [-h]' \
    'Control script for GitHub repository' \
    '
    -l            : Login to GitHub
    -s            : Show repository deployment keys
    -a            : Add repository deployment key
    -r            : Remove repository deployment key
    ' '
    -h            : Show help
    ' '
    -e Environment: Environment name
    -p Profile    : Configuration profile
    -i KeyID      : Deployment Key ID
    -V Verbose    : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
    -D Debug      : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
    '
}

#
# Main
#

declare github_main_command="$BL64_VAR_NULL"
declare github_main_debug="$BL64_DBG_TARGET_NONE"
declare github_main_option=''
declare github_main_verbose="$BL64_MSG_VERBOSE_APP"
declare github_main_environment="$BL64_VAR_NULL"
declare github_main_profile="$BL64_VAR_DEFAULT"
declare github_main_key_id="$BL64_VAR_NULL"

(($# == 0)) && github_main_help && exit 1
while getopts ':lsare:p:i:V:D:h' github_main_option; do
  case "$github_main_option" in
  l) github_main_command='login' ;;
  s) github_main_command='key_show' ;;
  a) github_main_command='key_add' ;;
  r) github_main_command='key_remove' ;;
  e) github_main_environment="$OPTARG" ;;
  p) github_main_profile="$OPTARG" ;;
  i) github_main_key_id="$OPTARG" ;;
  V) github_main_verbose="$OPTARG" ;;
  D) github_main_debug="$OPTARG" ;;
  h) github_main_help && exit 0 ;;
  *) github_main_help && exit 1 ;;
  esac
done
bl64_dbg_set_level "$github_main_debug" && bl64_msg_set_level "$github_main_verbose" || exit $?
github_main_initialize "$github_main_command" "$github_main_environment" "$github_main_profile" "$github_main_key_id" || exit $?

bl64_msg_show_batch_start "${github_main_command}"
case "$github_main_command" in
'login') "github_main_${github_main_command}" ;;
'key_show') "github_main_${github_main_command}" "$github_main_environment" ;;
'key_add') "github_main_${github_main_command}" "$github_main_environment" ;;
'key_remove') "github_main_${github_main_command}" "$github_main_environment" "$github_main_key_id" ;;
*) bl64_check_alert_parameter_invalid "$github_main_command" ;;
esac
bl64_msg_show_batch_finish $? "$github_main_command"
