---
object: "gitops64.fluxcd"
version: "1.0.0"
fluxcd:
  timeout: "10m"
  cluster:
    owner: "X_GITHUB_REPO_OWNER_X"
    repository: "test-gitops"
    branch: "main"
    path: "var/dev/fluxcd"
    context: "dev"
...
