---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/infrastructure/rook/fluxcd/default"

patches:
  - path: "helm-repository-rook-ceph.patch.yaml"
  - path: "helm-repository-rook-ceph-cluster.patch.yaml"
  - path: "helm-release-rook-ceph.patch.yaml"
  - path: "helm-release-rook-ceph-cluster.patch.yaml"
...
