#!/usr/bin/env bash
# Template: 1.1.0
#######################################
# ArgoCD / Control Service
#
# Control script for ArgoCD service
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/gitops64
# Version: 2.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=lib/bl64/bashlib64.bash
source 'lib/bl64/bashlib64.bash' || { echo "Error: unable to load bashlib64" && exit 1; }

# shellcheck source=src/gitops64/bl64-lib/setup
source 'src/gitops64/bl64-lib/setup' || { echo "Error: unable to load bashlib64" && exit 1; }

#
# Globals
#

export ARGOCD_CONTROL_ARGOCD_BIN="${ARGOCD_CONTROL_ARGOCD_BIN:-/usr/local/bin/argocd}"
export ARGOCD_CONTROL_GH_BIN="${ARGOCD_CONTROL_GH_BIN:-/usr/bin/gh}"

declare ARGOCD_CONTROL_REPOSITORY_NAME='argo'
declare ARGOCD_CONTROL_REPOSITORY_URL='https://argoproj.github.io/argo-helm'
declare ARGOCD_CONTROL_CHART_NAME='argocd'
declare ARGOCD_CONTROL_KEY_PRIVATE=''
declare ARGOCD_CONTROL_VAULT_ADMIN=''

#
# Functions
#

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function argocd_control_run_cli() {
  bl64_dbg_app_show_function "$@"
  local access=''
  [[ "$ARGOCD_SERVER_ACCESS" == 'port-forward' ]] && access="--port-forward --port-forward-namespace ${ARGOCD_CLUSTER_NAMESPACE}"
  # shellcheck disable=SC2086
  "$ARGOCD_CONTROL_ARGOCD_BIN" \
    $access \
    "$@"
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function argocd_control_secret_ssh_add() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"
  bl64_msg_show_task "create K8S secret for GIT SSH access"
  # shellcheck disable=SC2086
  argocd_control_run_cli \
    repo add \
    --ssh-private-key-path "$ARGOCD_CONTROL_KEY_PRIVATE" \
    "$ARGOCD_GITOPS_REPOSITORY"
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function argocd_control_remove() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"

  bl64_msg_show_task "remove ArgoCD form Kubernetes Cluster (${environment})"
  bl64_ui_ask_confirmation \
    'Please confirm this destructive action by typing:' 'YES' &&
    bl64_hlm_run_helm \
      uninstall \
      --wait \
      --namespace "$ARGOCD_CLUSTER_NAMESPACE" \
      "$ARGOCD_CONTROL_CHART_NAME" ||
    return $?
  if [[ -f "$ARGOCD_CONTROL_VAULT_ADMIN" ]]; then
    bl64_fs_rm_file "$ARGOCD_CONTROL_VAULT_ADMIN"
  fi
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function argocd_control_login() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"
  local password=''

  bl64_msg_show_task "login to ArgoCD cluster (${environment})"
  # shellcheck disable=SC2086
  password="$(<$ARGOCD_CONTROL_VAULT_ADMIN)" &&
    argocd_control_run_cli \
      login \
      --username "$ARGOCD_ADMIN_USER" \
      --password "$password"
}

# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function argocd_control_deploy() {
  bl64_dbg_app_show_function "$@"
  local environment="$1"
  local profile="$2"
  local chart_source='argo/argo-cd'
  local chart_values="${GITOPS64_PATH_ETC}/${environment}/argocd/${profile}/chart-values.yaml"
  local admin_secret='argocd-initial-admin-secret'

  bl64_check_file "$chart_values" ||
    return $?

  bl64_msg_show_task 'register ArgoCD Helm Repository'
  bl64_hlm_repo_add "$ARGOCD_CONTROL_REPOSITORY_NAME" "$ARGOCD_CONTROL_REPOSITORY_URL"

  bl64_msg_show_task "deploy ArgoCD to Kubernetes Cluster (${environment})"
  bl64_hlm_chart_upgrade \
    "${HOME}/.kube/config" \
    "$ARGOCD_CLUSTER_NAMESPACE" \
    "$ARGOCD_CONTROL_CHART_NAME" \
    "$chart_source" \
    --values "$chart_values" ||
    return $?

  bl64_msg_show_task "store initial admin password (${ARGOCD_CONTROL_VAULT_ADMIN})"
  if [[ -f "$ARGOCD_CONTROL_VAULT_ADMIN" ]]; then
    bl64_msg_show_warning 'password already store. Reusing existting one'
    # shellcheck disable=SC2005
    echo "$(
      bl64_k8s_run_kubectl \
        "$BL64_VAR_DEFAULT" \
        get secret \
        --namespace "$ARGOCD_CLUSTER_NAMESPACE" \
        --output jsonpath="{.data.password}" \
        "$admin_secret" |
        bl64_txt_run_base64 --decode
    )" >"$ARGOCD_CONTROL_VAULT_ADMIN"
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
# Required to prevent false positive on YAML generated shell-env
# shellcheck disable=SC2154
function argocd_control_initialize() {
  bl64_dbg_app_show_function "$@"
  local command="$1"
  local environment="$2"
  local profile="$3"

  # shellcheck disable=SC2015
  bl64_check_parameter 'command' &&
    bl64_check_parameter 'environment' ||
    { argocd_control_help && return 1; }

  bl64_check_command "$ARGOCD_CONTROL_ARGOCD_BIN" &&
    bl64_check_command "$ARGOCD_CONTROL_GH_BIN" &&
    bl64_k8s_setup &&
    bl64_hlm_setup ||
    return $?

  gitops64_initialize &&
    gitops64_setup_load 'all' 'argocd' "$profile" 'setup' &&
    gitops64_setup_load "$environment" 'argocd' "$profile" 'service' &&
    bl64_check_export 'ARGOCD_CLUSTER_CONTEXT' &&
    bl64_check_export 'ARGOCD_CLUSTER_NAMESPACE' &&
    bl64_check_export 'ARGOCD_GITOPS_REPOSITORY' ||
    return $?
  ARGOCD_CONTROL_KEY_PRIVATE="${GITOPS64_PATH_VAULT}/${environment}/${GITOPS64_KEY_DEPLOYMENT_PRIVATE}"
  ARGOCD_CONTROL_VAULT_ADMIN="${GITOPS64_PATH_VAULT}/${environment}/${ARGOCD_ADMIN_VAULT}"

  if [[ "$command" == 'secret_ssh_add' ]]; then
    bl64_check_file "$ARGOCD_CONTROL_KEY_PRIVATE" 'missing deploy key file. Please generate one and retry' ||
      return $?
  elif [[ "$command" == 'login' ]]; then
    bl64_check_file "$ARGOCD_CONTROL_VAULT_ADMIN" 'missing admin password file. Please generate one and retry' ||
      return $?
  fi
}

#######################################
# Show script usage description
#
# Arguments:
#   None
# Outputs:
#   Command line format and description
# Returns:
#   0
#######################################
function argocd_control_help() {
  bl64_msg_show_usage \
    '<-d|-r|-k|-l> -e Environment [-p Profile] [-V Verbose] [-D Debug] [-h]' \
    'Manage ArgoCD service deployment' \
    '
    -d            : Deploy ArgoCD to Kubernetes Cluster
    -r            : Remove ArgoCD from Kubernetes Cluster
    -k            : Register private GIT repository
    -l            : Login to ArgoCD server
    ' '
    -h            : Show help
    ' '
    -e Environment: Environment name
    -p Profile    : Configuration profile
    -V Verbose    : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
    -D Debug      : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
    '
}

#
# Main
#

declare argocd_control_command="$BL64_VAR_NULL"
declare argocd_control_debug="$BL64_DBG_TARGET_NONE"
declare argocd_control_option=''
declare argocd_control_verbose="$BL64_MSG_VERBOSE_APP"
declare argocd_control_environment="$BL64_VAR_NULL"
declare argocd_control_profile="$BL64_VAR_DEFAULT"

(($# == 0)) && argocd_control_help && exit 1
while getopts ':drlke:p:V:D:h' argocd_control_option; do
  case "$argocd_control_option" in
  d) argocd_control_command='deploy' ;;
  r) argocd_control_command='remove' ;;
  l) argocd_control_command='login' ;;
  k) argocd_control_command='secret_ssh_add' ;;
  e) argocd_control_environment="$OPTARG" ;;
  p) argocd_control_profile="$OPTARG" ;;
  V) argocd_control_verbose="$OPTARG" ;;
  D) argocd_control_debug="$OPTARG" ;;
  h) argocd_control_help && exit 0 ;;
  *) argocd_control_help && exit 1 ;;
  esac
done
bl64_dbg_set_level "$argocd_control_debug" && bl64_msg_set_level "$argocd_control_verbose" || exit $?
argocd_control_initialize "$argocd_control_command" "$argocd_control_environment" "$argocd_control_profile" || exit $?

bl64_msg_show_batch_start "$argocd_control_command"
case "$argocd_control_command" in
'deploy' ) "argocd_control_${argocd_control_command}" "$argocd_control_environment" "$argocd_control_profile";;
'remove' | 'login') "argocd_control_${argocd_control_command}" "$argocd_control_environment" ;;
'secret_ssh_add') "argocd_control_${argocd_control_command}" "$argocd_control_environment" ;;
*) bl64_check_alert_parameter_invalid "$argocd_control_command" ;;
esac
bl64_msg_show_batch_finish $? "$argocd_control_command"
