---
apiVersion: "mysql.oracle.com/v2"
kind: "InnoDBCluster"
metadata:
  name: "innodb-shared"
  namespace: "innodb-shared"
spec:
  tlsUseSelfSigned: true
  version: "8.2.0"
  instances: 1
  router:
    instances: 1
...
