---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../src/resources/innodb-shared/kustomize/argocd"
patches:
  - path: "innodb-cluster.patch.yaml"
...
