---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "root-resources"
  namespace: "argocd"
spec:
  source:
    repoURL: "git@github.com:itc64-dev/test-gitops.git"
#    targetRevision: "HEAD"
    targetRevision: "feature/update"
...
