---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/applications/http-echo/kustomize/istio-api"
patches:
  - path: "namespace.patch.yaml"
  - path: "deployment.patch.yaml"
...
