---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  name: "gateway-api"
  namespace: "gateway-api"
spec:
  interval: "1m0s"
  timeout: "5m0s"
  prune: true
  wait: true
...
