---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "istiod"
  namespace: "istio-system"
spec:
  chart:
    spec:
      chart: "istiod"
      reconcileStrategy: "ChartVersion"
      sourceRef:
        kind: HelmRepository
        name: "istio"
...
