---
apiVersion: "argoproj.io/v1alpha1"
kind: "AppProject"
metadata:
  name: "opensearch"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  sourceRepos:
    - '*'
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "opensearch"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
...
