---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/infrastructure/istio-system/argocd/default"
patches:
  - path: "application-base.patch.yaml"
  - path: "application-istiod.patch.yaml"
...
