---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "base"
  namespace: "istio-system"
spec:
  interval: "60m"
  chart:
    spec:
      chart: "base"
      version: "1.20.0"
...
