---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../src/istio-system/kustomize"

patches:
  - path: "helm-repository.patch.yaml"
  - path: "helm-release-base.patch.yaml"
  - path: "helm-release-istiod.patch.yaml"
...
