---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "httpbin"
  namespace: "httpbin"
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "v1"
  template:
    metadata:
      labels:
        version: "v1"
...
