---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "metallb"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "metallb"
  source:
    chart: "metallb"
    repoURL: "https://metallb.github.io/metallb"
    helm:
      valuesObject: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "metallb"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
...
