---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "prometheus"
  namespace: "prometheus"
spec:
  interval: "60m"
  chart:
    spec:
      chart: "prometheus"
      version: "25.8.2"
      interval: "6h"
  values:
    server:
      resources:
        limits:
          cpu: "400m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"
...
