---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  name: "gateway-api"
  namespace: "gateway-api"
spec:
  path: "config/crd"
  sourceRef:
    kind: "GitRepository"
    name: "gateway-api"
...
