#!/usr/bin/env bash

declare environment='dev'
declare profile='medium'
declare control='./src/kubernetes/minikube/bl64/control'

"$control" -e "$environment" -p "$profile" -s &&
  "$control" -e "$environment" -p "$profile" -t
