---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../src/infrastructure/grafana/kustomize/argocd"
patches:
  - path: "application.patch.yaml"
  - path: "application-loki.patch.yaml"
  - path: "application-prometheus.patch.yaml"
...
