---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "http-echo"
  namespace: "http-echo"
spec:
  type: "ClusterIP"
  selector:
    app: "http-echo"
  ports:
    - name: "http"
      port: 8080
...
