---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../src/infrastructure/metallb/kustomize/argocd"
patches:
  - path: "application.patch.yaml"
  - path: "ip-address-pool.patch.yaml"
...
