---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "fluent-bit"
  namespace: "argocd"
spec:
  source:
    targetRevision: "0.40.0"
    helm:
      valuesObject:
        logLevel: "info"
        config:
          filters: |
            [FILTER]
                Name                   kubernetes
                Match                  kube.*
                Merge_Log              On
                Keep_Log               Off
                K8S-Logging.Parser     On
                K8S-Logging.Exclude    On
                Labels                 On
                Annotations            On
          outputs: |
            [OUTPUT]
                name                   loki
                match                  *
                host                   loki.loki.svc.cluster.local
                port                   3100
                labels                 job=fluentbit
                label_keys             $sub['stream']
                auto_kubernetes_labels on
                tenant_id              fluent-bit-agent
...
