---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "sealed-secrets"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "sealed-secrets"
  source:
    chart: "sealed-secrets"
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    helm:
      valuesObject:
        # Required to match kubeseal default operator name
        fullnameOverride: "sealed-secrets-controller"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "sealed-secrets"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
...
