---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/applications/httpbin/kustomize/loadbalancer"
patches:
  - path: "deployment.patch.yaml"
...
