---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "metrics-server"
  namespace: "metrics-server"
spec:
  interval: "60m"
  chart:
    spec:
      chart: "metrics-server"
      version: "3.11.0"
...
