---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../src/metrics-server/kustomize"

patches:
  - path: "helm-repository.patch.yaml"
  - path: "helm-release.patch.yaml"
...
