---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "istio-system-base"
  namespace: "istio-system"
spec:
  chart:
    spec:
      chart: "base"
      reconcileStrategy: "ChartVersion"
      sourceRef:
        kind: "HelmRepository"
        name: "istio"
...
