---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../src/infrastructure/cert-manager/kustomize/fluxcd"

patches:
  - path: "helm-repository.patch.yaml"
  - path: "helm-release.patch.yaml"
...
