---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/infrastructure/istio-ingress/fluxcd/istio-api"
patches:
  - path: "helm-release.patch.yaml"
...
