---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  name: "cert-manager"
  namespace: "flux-system"
spec:
  interval: "1m0s"
  timeout: "5m0s"
  prune: true
  wait: true
  path: "./etc/dev/cert-manager/fluxcd/default"
  dependsOn:
    - name: "metrics-server"
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
...
