---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "istio-system-istiod"
  namespace: "istio-system"
spec:
  interval: "60m"
  chart:
    spec:
      chart: "istiod"
      version: "1.20.0"
  values:
    global:
      logAsJson: false
      logging:
        level: "default:info"
      proxy:
        logLevel: "info"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "2000m"
            memory: "1024Mi"
...
