---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "../../../../../../src/infrastructure/cert-manager/argocd/default"
patches:
  - path: "application-cert-manager.patch.yaml"
  - path: "application-trust-manager.patch.yaml"
...
