---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "wordpress"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "wordpress"
  source:
    chart: "wordpress"
    repoURL: "https://charts.bitnami.com/bitnami"
    helm:
      valuesObject: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "wordpress"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
...
