---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "namespace.yaml"
  - "service-account.yaml"
  - "deployment.yaml"
  # disabled # - "service-nodeport.yaml"
  - "service-clusterip.yaml"
  # disabled # - "http-route.yaml"
  - "virtual-service.yaml"
...
