---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "istio-system-istiod"
  namespace: "argocd"
spec:
  source:
    targetRevision: "1.20.0"
    helm:
      valuesObject:
        global:
          logAsJson: false
          logging:
            level: "default:info"
          proxy:
            logLevel: "info"
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "2000m"
                memory: "1024Mi"
        telemetry:
          enabled: true
        v2:
          enabled: true
          prometheus:
            enabled: true
          stackdriver:
            enabled: false
        meshConfig:
          enablePrometheusMerge: true
...
