---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "gateway"
  namespace: "istio-ingress"
spec:
  interval: "60m"
  chart:
    spec:
      version: "1.20.0"
  values:
    podAnnotations:
      sidecar.istio.io/agentLogLevel: "info"
      sidecar.istio.io/logLevel: "info"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
...
