---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "httpbin"
  namespace: "httpbin"
spec:
  type: "ClusterIP"
  selector:
    app: "httpbin"
  ports:
    - name: "http"
      port: 8000
      targetPort: 80
...
