---
# Template: 1.2.0
name: "Lint / YAML"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"
      - "etc/**"
      - "var/**"

jobs:
  lint-yaml:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare dev environment"
        run: "./bin/dev-lib-installer64"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-lint-yamllint"
...
