---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "gateway"
  namespace: "istio-ingress"
spec:
  chart:
    spec:
      chart: "gateway"
      reconcileStrategy: "ChartVersion"
      sourceRef:
        kind: HelmRepository
        name: "istio"
        namespace: "istio-system"
...
