---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "cert-manager"
  namespace: "argocd"
spec:
  project: "cert-manager"
  source:
    chart: "cert-manager"
    repoURL: "https://charts.jetstack.io"
    helm:
      valuesObject:
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "cert-manager"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
...
